global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: notification-service
    scrape_interval: 5s
    scrape_timeout: 1s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets: ['notification-service:11000']
        labels:
          service: 'notification-service'
          server_name: tjdev