{
 "title": "Metrics",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Runner Service Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(runner_service_count[5m])",
     "legendFormat": "total count"
    },
    {
     "expr": "increase(runner_service_failed_count[5m])",
     "legendFormat": "fail count"
    }
   ]
  },
  {
   "title": "HTTP Request Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(http_request_duration_milliseconds_count[5m])"
    }
   ]
  },
  {
   "title": "Publisher Service  Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(publisher_service_count{exported_service=\"delivery\"}[5m])",
     "legendFormat": "delivery"
    },
    {
     "expr": "increase(publisher_service_count{exported_service=\"tj-dsp\"}[5m])",
     "legendFormat": "tj-dsp"
    },
    {
     "expr": "increase(publisher_service_count{exported_service=\"tj-ssp\"}[5m])",
     "legendFormat": "tj-ssp"
    }
   ]
  },
  {
   "title": "Runner Service Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(runner_service_duration_milliseconds_bucket{endpoint=\"notify\",method=\"notification-service\"}[5m]))",
     "legendFormat": "0.5 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, rate(runner_service_duration_milliseconds_bucket{endpoint=\"notify\",method=\"notification-service\"}[5m]))",
     "legendFormat": "0.9 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, rate(runner_service_duration_milliseconds_bucket{endpoint=\"notify\",method=\"notification-service\"}[5m]))",
     "legendFormat": "0.99 percentile"
    }
   ]
  },
  {
   "title": "Publisher Topic Count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(publisher_topic_count[5m])",
     "legendFormat": "# topics"
    }
   ]
  },
  {
   "title": "HTTP Request Duration  (Milliseconds)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(http_request_duration_milliseconds_bucket{endpoint=\"notify\",method=\"notification-service\"}[5m]))",
     "legendFormat": "0.5 percentile"
    },
    {
     "expr": "histogram_quantile(0.9, rate(http_request_duration_milliseconds_bucket{endpoint=\"notify\",method=\"notification-service\"}[5m]))",
     "legendFormat": "0.9 percentile"
    },
    {
     "expr": "histogram_quantile(0.99, rate(http_request_duration_milliseconds_bucket{endpoint=\"notify\",method=\"notification-service\"}[5m]))",
     "legendFormat": "0.99 percentile"
    }
   ]
  }
 ]
}